version: '3.8'

services:
  tomcat:
    build:
      context: .
      dockerfile: dockerfile_tomcat
    container_name: tomcat_container
    ports:
      - "8009:8009"
      - "8080:8080"
    volumes:
      - ./tomcat/server_local.xml:/usr/local/tomcat/conf/server.xml
