FROM tomcat:9.0

# アプリケーションをコンテナにコピー
# COPY ./my-webapp.war /usr/local/tomcat/webapps/

# Tomcatの管理ポータルを有効化する場合
# COPY ./tomcat-users.xml /usr/local/tomcat/conf/tomcat-users.xml

# ポート8080を公開
EXPOSE 8080

# Tomcatを起動
CMD ["catalina.sh", "run"]

