version: '3.8'

services:
  tomcat:
    build:
      context: .
      dockerfile: dockerfile_tomcat
    container_name: tomcat_container
    ports:
      - "8009:8009"
    volumes:
      - ./tomcat/server_local.xml:/usr/local/tomcat/conf/server.xml
      - ./tomcat/application/HelloWorldApp/target/helloworldApp.war:/usr/local/tomcat/webapps/helloworldApp.war
