# Tomcatイメージのベースとして公式のTomcatイメージを使用
FROM tomcat:9.0

# AJPコネクタを有効にするための設定ファイルをコピー
COPY ./tomcat/server_local.xml /usr/local/tomcat/conf/server.xml

# アプリケーションをコンテナにコピー
COPY ./tomcat/application/HelloWorldApp/target/helloworldApp.war /usr/local/tomcat/webapps/

# ポート8080と8009(AJP用)を公開
EXPOSE 8009

# Tomcatを起動
CMD ["catalina.sh", "run"]
