version: '3.8'

services:
  mysql:
    build:
      context: .
      dockerfile: dockerfile_mysql
    container_name: mysql_container
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/dump.sql:/docker-entrypoint-initdb.d/dump.sql

volumes:
  mysql_data:
